#!/bin/bash

echo "🔑 Sanity Write Token Setup"
echo "========================="
echo ""
echo "1. Visit: https://manage.sanity.io/"
echo "2. Select your project: 5cywtc7a"
echo "3. Navigate to: API → Tokens"
echo "4. Click 'Add API token'"
echo "5. Give it a name: 'Migration Token'"
echo "6. Set permissions to 'Editor'"
echo "7. Copy the generated token"
echo ""
echo "Then run this command with your token:"
echo ""
echo "  export SANITY_WRITE_TOKEN='your-token-here'"
echo ""
echo "Or add it to your .env.local file:"
echo ""
echo "  SANITY_WRITE_TOKEN=your-token-here"
echo ""
echo "Once set up, run the migration:"
echo ""
echo "  node migrate-creators.js"
echo ""
