import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'youtubeId',
  title: 'YouTube ID',
  type: 'document',
  groups: [
    {
      name: 'hero',
      title: 'Hero / Intro Section',
      default: true,
    },
    {
      name: 'sideInfo',
      title: 'Side Info',
    },
    {
      name: 'visualIdentity',
      title: 'Visual Identity',
    },
    {
      name: 'concept',
      title: 'Concept',
    },
  ],
  fields: [
    // Hero / Intro Section
    defineField({
      name: 'channel_number',
      title: 'Channel Number',
      type: 'string',
      group: 'hero',
      description: 'e.g., 01',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      group: 'hero',
      options: {
        list: [
          {title: 'Gaming', value: 'Gaming'},
          {title: 'Lifestyle', value: 'Lifestyle'},
          {title: 'Education', value: 'Education'},
          {title: 'Technology', value: 'Technology'},
          {title: 'Entertainment', value: 'Entertainment'},
          {title: 'Business', value: 'Business'},
          {title: 'Health & Fitness', value: 'Health & Fitness'},
          {title: 'Food & Cooking', value: 'Food & Cooking'},
          {title: 'Travel', value: 'Travel'},
          {title: 'Music', value: 'Music'},
          {title: 'Sports', value: 'Sports'},
          {title: 'News', value: 'News'},
          {title: 'Comedy', value: 'Comedy'},
          {title: 'Arts & Culture', value: 'Arts & Culture'},
          {title: 'Science', value: 'Science'},
          {title: 'Other', value: 'Other'},
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'channel_name',
      title: 'Channel Name',
      type: 'string',
      group: 'hero',
      description: 'Official channel name',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'hero',
      options: {
        source: 'channel_name',
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'intro_description',
      title: 'Intro Description',
      type: 'richBody',
      group: 'hero',
      description: 'Short description of the channel',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'cta_button_url',
      title: 'CTA Button URL',
      type: 'url',
      group: 'hero',
      description: 'Link to the YouTube channel',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero Image',
      type: 'array',
      of: [{type: 'imageWithAlt'}],
      group: 'hero',
      options: {
        layout: 'grid',
      },
      validation: (Rule) => Rule.max(1),
      description: 'Main hero image for homepage project showcase',
    }),
    defineField({
      name: 'logoImage',
      title: 'Logo Image',
      type: 'array',
      of: [{type: 'imageWithAlt'}],
      group: 'hero',
      options: {
        layout: 'grid',
      },
      validation: (Rule) => Rule.max(1),
      description: 'Channel logo for branding and identification',
    }),
    defineField({
      name: 'thumbnailExample',
      title: 'Thumbnail Example Image',
      type: 'array',
      of: [{type: 'imageWithAlt'}],
      group: 'hero',
      options: {
        layout: 'grid',
      },
      validation: (Rule) => Rule.max(1),
      description: 'Example thumbnail showcasing channel style',
    }),

    // Side Info
    defineField({
      name: 'channel',
      title: 'Channel Owner/Creator',
      type: 'string',
      group: 'sideInfo',
      description: 'Channel owner or main creator\'s name',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'date_started',
      title: 'Date Started',
      type: 'date',
      group: 'sideInfo',
      description: 'When the channel began',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'focus',
      title: 'Focus',
      type: 'array',
      of: [{type: 'string'}],
      group: 'sideInfo',
      options: {
        list: [
          {title: 'Reviews', value: 'Reviews'},
          {title: 'Tutorials', value: 'Tutorials'},
          {title: 'Comedy', value: 'Comedy'},
          {title: 'Vlogs', value: 'Vlogs'},
          {title: 'Gaming', value: 'Gaming'},
          {title: 'Music', value: 'Music'},
          {title: 'Education', value: 'Education'},
          {title: 'Entertainment', value: 'Entertainment'},
          {title: 'Lifestyle', value: 'Lifestyle'},
          {title: 'Technology', value: 'Technology'},
          {title: 'Cooking', value: 'Cooking'},
          {title: 'Travel', value: 'Travel'},
          {title: 'Fitness', value: 'Fitness'},
          {title: 'News', value: 'News'},
          {title: 'Other', value: 'Other'},
        ],
        layout: 'tags',
      },
      description: 'e.g., "Reviews", "Tutorials", "Comedy"',
    }),
    defineField({
      name: 'share_links',
      title: 'Share Links',
      type: 'shareLinks',
      group: 'sideInfo',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'teamMembers',
      title: 'Team Members',
      type: 'array',
      of: [{
        type: 'reference',
        to: [{type: 'teamMember'}],
      }],
      group: 'sideInfo',
      description: 'Team members who work on this channel',
    }),

    // Visual Identity
    defineField({
      name: 'visual_identity_subtitle',
      title: 'Visual Identity Subtitle',
      type: 'string',
      group: 'visualIdentity',
      description: 'Short line under "Visual Identity"',
    }),
    defineField({
      name: 'visual_identity_description',
      title: 'Visual Identity Description',
      type: 'richBody',
      group: 'visualIdentity',
      description: 'Explanation of visual style',
    }),
    defineField({
      name: 'visual_identity_bullets',
      title: 'Visual Identity Bullets',
      type: 'array',
      of: [{type: 'string'}],
      group: 'visualIdentity',
      description: 'Key branding/identity aspects',
    }),
    defineField({
      name: 'typography',
      title: 'Typography',
      type: 'array',
      of: [{type: 'typography'}],
      group: 'visualIdentity',
      description: 'Fonts used in the channel branding',
    }),
    defineField({
      name: 'colors',
      title: 'Colors',
      type: 'array',
      of: [{type: 'colors'}],
      group: 'visualIdentity',
      description: 'Brand colors with hex codes',
    }),
    defineField({
      name: 'visual_identity_images',
      title: 'Visual Identity Images',
      type: 'array',
      of: [{type: 'imageWithAlt'}],
      group: 'visualIdentity',
      description: 'Logos, banners, sample thumbnails',
    }),

    // Concept
    defineField({
      name: 'concept_subtitle',
      title: 'Concept Subtitle',
      type: 'string',
      group: 'concept',
      description: 'Short line under "Concept"',
    }),
    defineField({
      name: 'concept_text_block_1',
      title: 'Concept Text Block 1',
      type: 'richBody',
      group: 'concept',
      description: 'Core channel concept / philosophy',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'concept_text_block_2',
      title: 'Concept Text Block 2',
      type: 'richBody',
      group: 'concept',
      description: 'Extra details, target audience, inspiration',
    }),
    defineField({
      name: 'concept_images',
      title: 'Concept Images',
      type: 'array',
      of: [{type: 'imageWithAlt'}],
      group: 'concept',
      description: 'Screenshots, BTS, video stills',
    }),
  ],
  preview: {
    select: {
      title: 'channel_name',
      channelNumber: 'channel_number',
      category: 'category',
      creator: 'channel',
    },
    prepare({title, channelNumber, category, creator}) {
      return {
        title: `${channelNumber ? `${channelNumber} - ` : ''}${title || 'Untitled YouTube ID'}`,
        subtitle: [category, creator].filter(Boolean).join(' • '),
      }
    },
  },
})
